musicData = [
    {
        "page_name": "Redstone",
        "title": "Redstone",
        "image": "images/redstone.png",
        // "spotify": "https://open.spotify.com/track/6R8hcFVbkPZlgFmituX7lS?si=389d2d2ee4e749e0",
        "youtube": "https://www.youtube.com/watch?v=0sVdj4Eof-k",
        // "apple": "https://music.apple.com/ng/album/inimigo-do-tempo-single/1791466716",
        // "deezer": "https://deezer.page.link/jyHYDEquA35VmY3aA",
        // "amazon": "https://music.amazon.com/albums/B0DTDNQH78",
        // "tidal": "https://tidal.com/browse/track/412418719",
    },
    {
        "page_name": "InimigoDoTempo",
        "title": "Inimigo do Tempo",
        "image": "images/inimigodotempo.png",
        "spotify": "https://open.spotify.com/track/6R8hcFVbkPZlgFmituX7lS?si=389d2d2ee4e749e0",
        "youtube": "https://www.youtube.com/watch?v=TKoJ6ACXm1E",
        "apple": "https://music.apple.com/ng/album/inimigo-do-tempo-single/1791466716",
        "deezer": "https://deezer.page.link/jyHYDEquA35VmY3aA",
        "amazon": "https://music.amazon.com/albums/B0DTDNQH78",
        "tidal": "https://tidal.com/browse/track/412418719",
    },
    {
        "page_name": "NoTato",
        "title": "No Tato",
        "image": "images/notato.png",
        "spotify": "https://open.spotify.com/track/6mtQp8pfFZ13DiyMnhwJAT?si=0aca03ef6e134f42",
        "youtube": "https://www.youtube.com/watch?v=mb3PCNyqy1s",
        "apple": "https://music.apple.com/ng/album/no-tato-single/1774211592",
        "amazon": "https://music.amazon.com/tracks/B0DK2ZGT74",
        "deezer": "https://deezer.page.link/SfeFDhwrFHBioMHF6",
        "tidal": "https://tidal.com/browse/track/393248508",
    },
    {
        "page_name": "Marrenta",
        "title": "Marrenta",
        "image": "images/marrenta.png",
        "spotify": "https://open.spotify.com/track/6zk3xlNHUb3SNlBhC7iQC8?si=ab03de0647264ec1",
        "youtube": "https://www.youtube.com/watch?v=RBYpqqvuLlQ",
        "apple": "https://music.apple.com/ng/album/marrenta-single/1743582712",
        "deezer": "https://deezer.page.link/fLRfpAy42sFJje2q6",
        "tidal": "https://tidal.com/browse/track/360002256",
    },
    // {
    //     "page_name": "HazeOuKush",
    //     "title": "Haze ou Kush",
    //     "image": "images/haze ou kush.png",
    //     "spotify": "https://open.spotify.com/track/5wvzgUqQDQAa4NJbustatv?si=615d2916419e41d6",
    //     "youtube": "https://www.youtube.com/watch?v=l1pqs1PGUPE",
    //     "apple": "https://music.apple.com/ng/album/haze-ou-kush-single/1743579581",
    //     "deezer": "https://deezer.page.link/ZgHujHWBSJQJzXXLA",
    //     "tidal": "https://tidal.com/browse/track/359998438",
    // },
    // {
    //     "page_name": "Aduka",
    //     "title": "Aduka",
    //     "image": "images/aduka.png",
    //     "spotify": "https://open.spotify.com/track/4TBd3TQ4NDOlyLY1aPsc7m?si=8a8a55b41dcb406b",
    //     "youtube": "https://www.youtube.com/watch?v=_aDxTV8V4kk",
    //     "apple": "https://music.apple.com/us/album/aduka/1732086353?i=1732086355",
    //     "amazon": "https://music.amazon.com/albums/B0CW269G9T?marketplaceId=ART4WZ8MWBX2Y&musicTerritory=CA&ref=dm_sh_tr0XVAKz521slfrUklEYoSDWT",
    //     "deezer": "https://deezer.page.link/F1RKxjYZ5aiXzzVA8",
    // },
    // {
    //     "page_name": "PosturaDeEmpresaria",
    //     "title": "Postura de Empresária",
    //     "image": "images/postura de empresaria.png",
    //     "spotify": "https://open.spotify.com/track/1qBJ2Byh9ebhxpqoO4ygu4?si=db34bbe69cde421f",
    //     "youtube": "https://www.youtube.com/watch?v=TjxK8j5yLDQ&ab_channel=yKouhai",
    //     "apple": "https://music.apple.com/us/album/postura-de-empres%C3%A1ria-single/1677652308",
    //     "deezer": "https://deezer.page.link/5iJyBtcrb7DZkRSA6",
    //     "tidal": "https://tidal.com/browse/album/282288980",
    // },
    // {
    //     "page_name": "EuNumQuarto",
    //     "title": "[EP] Eu Num Quarto",
    //     "image": "images/Eu num quarto.png",
    //     "spotify": "https://open.spotify.com/album/5YYqJl74SveMAIDW2XGQ9z?si=1I3ChnKgQUybC_k1eZtqYA",
    //     "youtube": "https://www.youtube.com/watch?v=D1003-XQJU0&list=PLoLpLgc9S_WNRacQueN6rSm7V9yiRoxv8&ab_channel=yKouhai",
    //     "apple": "https://music.apple.com/us/album/eu-num-quarto/1654429592",
    //     "amazon": "https://music.amazon.com/albums/B0CW269G9T?marketplaceId=ART4WZ8MWBX2Y&musicTerritory=CA&ref=dm_sh_tr0XVAKz521slfrUklEYoSDWT",
    //     "deezer": "https://deezer.page.link/F1RKxjYZ5aiXzzVA8",
    //     "tidal": "https://tidal.com/browse/album/297412033",
    // }
]
